# This is a basic workflow to help you get started with Actions

name: DEPLOY - PRD

run-name: "PRD-${{ vars.RUNNAME }}${{ github.event.workflow_run.run_number }}"

# Controls when the workflow will run
on:
  # Se gatilla cuando el workflow DEPLOY - UAT se completa
  workflow_run:
    workflows: ["DEPLOY - UAT"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # # Descarga el archivo de versión del workflow DEPLOY - UAT
      # - name: Download version artifact from DEPLOY - UAT
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: version-artifact
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     run-id: ${{ github.event.workflow_run.id }}

      # Lee la versión desde el archivo
      - name: Read version
        run: |
          VERSION=$(cat version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # # Descarga el artefacto del repositorio del workflow DEPLOY - UAT
      # - name: Download repository archive from DEPLOY - UAT
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: repository-archive
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     run-id: ${{ github.event.workflow_run.id }}

      # # Extrae el archivo zip
      # - name: Extract repository archive
      #   run: unzip -q repository-*.zip -d .

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploying version ${{ env.VERSION }} to PRD

      # Runs a set of commands using the runners shell
      - name: Run deployment script
        run: |
          echo Starting PRD deployment,
          echo deploying version ${{ env.VERSION }} to Production environment.
