# This is a basic workflow to help you get started with Actions

name: BUILD - DEV

run-name: "CI-${{ vars.RUNNAME }}${{ github.run_number }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    version: 1.0.${{ github.run_number }}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # # Comprime todos los archivos del repositorio
      # - name: Compress repository
      #   run: zip -r repository-${{ env.version }}.zip . -x "*.git*" ".github/workflows/*"

      # # Sube el archivo comprimido como artefacto
      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: repository-archive
      #     path: repository-${{ env.version }}.zip
      #     retention-days: 30

      # Sube el archivo de versión como artefacto
      - name: Save version to artifact
        run: echo "${{ env.version }}" > version.txt

      # Sube el archivo de versión como artefacto
      - name: Upload version artifact
        uses: actions/upload-artifact@v4
        with:
          name: version-artifact
          path: version.txt
          retention-days: 30
